[package]
name = "revhz"
version = "0.0.1"
authors = ["Josko Nikolic<josko.nikolic1@gmail.com>"]

[dependencies]
getopts = "0.2.11"
ioctl = "0.3.2"
num = "0.1.26"
mio = "0.4.1"

[[bin]]
name = "revhz"
